CREATE TABLE square (
   id serial PRIMARY KEY,
   square_id VARCHAR(50) UNIQUE NOT NULL,
   x SMALLINT NOT NULL,
   y SMALLINT NOT NULL,
   base64 VARCHAR(500000) NOT NULL,
   data_hora TIMESTAMP default CURRENT_TIMESTAMP
);